# Generated by Django 5.0.6 on 2024-09-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_receipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipes',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
